#!/usr/bin/env python3
"""Amalgamate mBMFF headers into a single header file."""

import argparse
import os
import re
import sys

REPO_URL = "https://github.com/Agrael1/mBMFF"
COPYRIGHT_YEAR = "2026"
COPYRIGHT_HOLDER = "Ilya \"Agrael\" Doroshenko"


def read_version(repo_root: str) -> str:
    path = os.path.join(repo_root, "VERSION")
    with open(path, "r", encoding="utf-8") as f:
        return f.read().strip()


def read_license(repo_root: str) -> str:
    path = os.path.join(repo_root, "LICENSE.txt")
    with open(path, "r", encoding="utf-8") as f:
        text = f.read()
    text = text.replace("[year]", COPYRIGHT_YEAR)
    text = text.replace("[fullname]", COPYRIGHT_HOLDER)
    return text


def build_comment_block(lines: list[str]) -> str:
    return "\n".join("// " + line if line else "//" for line in lines)


def resolve_include(path: str, search_dirs: list[str]) -> str | None:
    for d in search_dirs:
        candidate = os.path.join(d, path)
        if os.path.isfile(candidate):
            return os.path.normpath(candidate)
    return None


def amalgamate(entry_point: str, search_dirs: list[str], version: str) -> str:
    inlined: set[str] = set()
    guard_name = "MBMFF_AMALGAMATED_HPP"

    def process_file(filepath: str, depth: int = 0) -> list[str]:
        norm = os.path.normpath(filepath)
        if norm in inlined:
            return []
        inlined.add(norm)

        lines: list[str] = []
        skip_until_endif = 0
        with open(filepath, "r", encoding="utf-8") as f:
            for line in f:
                stripped = line.strip()

                if stripped.startswith("#ifdef MBMFF_ENABLE_CONSTEXPR_TEST"):
                    skip_until_endif += 1
                    continue

                if skip_until_endif:
                    if stripped.startswith("#endif"):
                        skip_until_endif -= 1
                    continue

                if stripped == "#pragma once":
                    continue

                m = re.match(r'#include\s+"([^"]+)"', stripped)
                if m:
                    included = m.group(1)
                    resolved = resolve_include(included, [os.path.dirname(filepath)] + search_dirs)
                    if resolved is None:
                        print(
                            f"Warning: could not resolve '{included}' (from {filepath})",
                            file=sys.stderr,
                        )
                        lines.append(line)
                        continue
                    content = process_file(resolved, depth + 1)
                    if content:
                        if lines and lines[-1].strip():
                            lines.append("\n")
                        lines.extend(content)
                        if not lines[-1].endswith("\n"):
                            lines.append("\n")
                    continue

                lines.append(line)

        return lines

    resolved = resolve_include(entry_point, search_dirs)
    if resolved is None:
        print(f"Error: entry point '{entry_point}' not found", file=sys.stderr)
        sys.exit(1)

    body = process_file(resolved)

    header = build_comment_block([
        "MIT License",
        "",
        f"Copyright (c) {COPYRIGHT_YEAR} {COPYRIGHT_HOLDER}",
        "",
        "Permission is hereby granted, free of charge, to any person obtaining a copy",
        "of this software and associated documentation files (the \"Software\"), to deal",
        "in the Software without restriction, including without limitation the rights",
        "to use, copy, modify, merge, publish, distribute, sublicense, and/or sell",
        "copies of the Software, and to permit persons to whom the Software is",
        "furnished to do so, subject to the following conditions:",
        "",
        "The above copyright notice and this permission notice shall be included in all",
        "copies or substantial portions of the Software.",
        "",
        'THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR',
        "IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,",
        "FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE",
        "AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER",
        "LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM",
        "OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE",
        "SOFTWARE.",
        "",
        f"Repository: {REPO_URL}",
        f"Version: {version}",
        "",
        "mBMFF -- single-header amalgamation",
        "Generated by tools/amalgamate.py",
    ])

    result = [
        f"#ifndef {guard_name}\n",
        f"#define {guard_name}\n",
        "\n",
        header + "\n",
        "\n",
    ]
    result.extend(body)
    result.append(f"\n#endif // {guard_name}\n")
    return "".join(result)


def main() -> None:
    parser = argparse.ArgumentParser(description="Amalgamate mBMFF headers")
    parser.add_argument(
        "--input",
        default=None,
        help="Input directory containing mbmff.hpp (default: include/mbmff)",
    )
    parser.add_argument(
        "--entry",
        default="mbmff.hpp",
        help="Entry point header (default: mbmff.hpp)",
    )
    parser.add_argument(
        "--output",
        default=None,
        help="Output file (default: stdout)",
    )
    args = parser.parse_args()

    script_dir = os.path.dirname(os.path.abspath(__file__))
    repo_root = os.path.abspath(os.path.join(script_dir, ".."))

    version = read_version(repo_root)
    _ = read_license(repo_root)  # validate it exists

    input_dir = args.input
    if input_dir is None:
        input_dir = os.path.join(repo_root, "include", "mbmff")

    entry_path = args.entry
    if not os.path.isabs(entry_path):
        entry_path = os.path.join(input_dir, entry_path)

    search_dirs = [input_dir, os.path.join(input_dir, "boxes")]

    output = amalgamate(entry_path, search_dirs, version)

    if args.output:
        out_dir = os.path.dirname(args.output)
        if out_dir:
            os.makedirs(out_dir, exist_ok=True)
        with open(args.output, "w", encoding="utf-8", newline="\n") as f:
            f.write(output)
    else:
        sys.stdout.write(output)


if __name__ == "__main__":
    main()
